services:
  train:
    build: .
    command: python -m src.main --data /data/cars_5m.csv.gz --out /models/carworth_hgbr_v1.joblib
    volumes:
      - ./data:/data
      - ./models:/models

  api:
    build: .
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8001
    environment:
      - MODEL_PATH=/models/carworth_hgbr_v1.joblib
      - MODEL_META=/models/carworth_hgbr_v1.meta.json
    volumes:
      - ./models:/models
    ports: ["8001:8001"]

