services:
  app:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
      - ./reports:/app/reports
    command: python -m src.main --data data/cars_sample_100k.csv.gz --out models/model.joblib --cv --plot