name: CI (Python)
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -U pip ruff mypy pytest pytest-cov scikit-learn fastapi uvicorn pydantic joblib
      - run: ruff check .
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - run: mypy --ignore-missing-imports .
      - run: pytest -q --maxfail=1 --disable-warnings --cov=src --cov-report=term
